import type { Edge, Node } from "@xyflow/react";
import type { ConstructData, SemModelV4ConstructAuthoring } from "../types";
import {
  convertNativeCovarianceToPresentationV4,
  convertNativeCovarianceToScientificV4,
  inspectNativeConstructAuthoringV4,
  inspectNativeCovarianceAuthoringV4,
  withNativeConstructEstimandV4,
} from "./semModelV4Authoring";
import {
  nativeWorkbenchConstructVariableIdV4,
  nativeWorkbenchObservedVariableIdV4,
} from "./nativeWorkbenchSemModelV4Adapter";

export const SEM_MODEL_V4_SCIENTIFIC_AUTHORING_WORKFLOW_VERSION = 1 as const;

export type NativeSemConstructChoiceV4 = "composite" | "common_factor";

export type NativeSemCovarianceChoiceV4 =
  | { kind: "model_covariance" }
  | { kind: "residual_covariance"; source_indicator: string; target_indicator: string }
  | { kind: "disturbance_covariance" }
  | { kind: "presentation_only" };

export type NativeSemCovarianceDraftV4 = NativeSemCovarianceChoiceV4 | { kind: "decision_required" };

export interface NativeSemScientificAuthoringDiagnosticV4 {
  code: string;
  subject: string;
  message: string;
  corrective_action: string;
}

export interface NativeSemConstructAuthoringProjectionV4 {
  workflow_version: typeof SEM_MODEL_V4_SCIENTIFIC_AUTHORING_WORKFLOW_VERSION;
  construct_id: string;
  choice: NativeSemConstructChoiceV4 | "decision_required" | "invalid";
  marker_indicator: string | null;
  marker_candidates: readonly string[];
  diagnostics: readonly NativeSemScientificAuthoringDiagnosticV4[];
}

export interface NativeSemCovarianceAuthoringProjectionV4 {
  workflow_version: typeof SEM_MODEL_V4_SCIENTIFIC_AUTHORING_WORKFLOW_VERSION;
  edge_id: string;
  choice: NativeSemCovarianceDraftV4 | { kind: "invalid" };
  source_construct_id: string;
  target_construct_id: string;
  source_indicator_candidates: readonly string[];
  target_indicator_candidates: readonly string[];
  source_is_endogenous: boolean;
  target_is_endogenous: boolean;
  diagnostics: readonly NativeSemScientificAuthoringDiagnosticV4[];
}

export type NativeSemConstructConfirmationResultV4 =
  | { ok: true; node: Node<ConstructData> }
  | { ok: false; diagnostics: readonly NativeSemScientificAuthoringDiagnosticV4[] };

export type NativeSemCovarianceConfirmationResultV4 =
  | { ok: true; edge: Edge }
  | { ok: false; diagnostics: readonly NativeSemScientificAuthoringDiagnosticV4[] };

export function projectNativeSemConstructAuthoringV4(
  node: Node<ConstructData>,
): NativeSemConstructAuthoringProjectionV4 {
  const inspection = inspectNativeConstructAuthoringV4(node);
  const markerCandidates = sortedUnique(node.data.indicators);
  const diagnostics: NativeSemScientificAuthoringDiagnosticV4[] = [];
  let choice: NativeSemConstructAuthoringProjectionV4["choice"] = "decision_required";
  let markerIndicator: string | null = null;

  if (node.data.semantic === "interaction" || node.data.semantic === "higher_order") {
    choice = "invalid";
    diagnostics.push(diagnostic(
      "sem_model_v4.authoring.construct_kind_not_supported",
      node.id,
      `${node.data.label || node.id} is generated by another model feature and cannot be reclassified here.`,
      "Edit its generating interaction or higher-order construct setup instead.",
    ));
  } else if (inspection.state === "invalid") {
    choice = "invalid";
    diagnostics.push(diagnostic(
      "sem_model_v4.authoring.construct_metadata_invalid",
      node.id,
      `Scientific authoring details for ${node.data.label || node.id} cannot be read safely.`,
      "Choose Composite or Common factor again.",
    ));
  } else if (inspection.state === "legacy_estimand_unspecified") {
    diagnostics.push(diagnostic(
      "sem_model_v4.authoring.construct_decision_required",
      node.id,
      `${node.data.label || node.id} still needs a factor-versus-composite decision.`,
      "Choose Composite when the construct is an explicitly weighted composite, or Common factor when indicators reflect an underlying factor.",
    ));
  } else if (inspection.state === "composite") {
    choice = "composite";
  } else {
    choice = "common_factor";
    markerIndicator = inspection.specification.marker_indicator;
    if (markerCandidates.length === 0) diagnostics.push(diagnostic(
      "sem_model_v4.authoring.common_factor_indicator_required",
      node.id,
      `${node.data.label || node.id} has no indicator available for marker identification.`,
      "Assign at least one indicator before confirming Common factor.",
    ));
    else if (markerIndicator !== null && !markerCandidates.includes(markerIndicator)) diagnostics.push(diagnostic(
      "sem_model_v4.authoring.marker_indicator_unknown",
      node.id,
      `Marker indicator ${markerIndicator} is not assigned to ${node.data.label || node.id}.`,
      "Choose one of this construct's assigned indicators as the marker.",
    ));
  }

  return freezeProjection({
    workflow_version: SEM_MODEL_V4_SCIENTIFIC_AUTHORING_WORKFLOW_VERSION,
    construct_id: node.id,
    choice,
    marker_indicator: markerIndicator,
    marker_candidates: markerCandidates,
    diagnostics: sortDiagnostics(diagnostics),
  });
}

export function confirmNativeSemConstructAuthoringV4(
  node: Node<ConstructData>,
  choice: NativeSemConstructChoiceV4,
  markerIndicator: string | null = null,
): NativeSemConstructConfirmationResultV4 {
  if (node.data.semantic === "interaction" || node.data.semantic === "higher_order") return failure(diagnostic(
    "sem_model_v4.authoring.construct_kind_not_supported",
    node.id,
    `${node.data.label || node.id} is generated by another model feature and cannot be reclassified here.`,
    "Edit its generating interaction or higher-order construct setup instead.",
  ));
  if (choice === "composite") return freezeProjection({ ok: true, node: withNativeConstructEstimandV4(node, { kind: "composite" }) });

  const candidates = sortedUnique(node.data.indicators);
  if (candidates.length === 0) return failure(diagnostic(
    "sem_model_v4.authoring.common_factor_indicator_required",
    node.id,
    `${node.data.label || node.id} has no indicator available for marker identification.`,
    "Assign at least one indicator before confirming Common factor.",
  ));
  const marker = markerIndicator?.trim() || candidates[0];
  if (!candidates.includes(marker)) return failure(diagnostic(
    "sem_model_v4.authoring.marker_indicator_unknown",
    node.id,
    `Marker indicator ${marker} is not assigned to ${node.data.label || node.id}.`,
    "Choose one of this construct's assigned indicators as the marker.",
  ));
  const specification: SemModelV4ConstructAuthoring = { kind: "common_factor", marker_indicator: marker };
  return freezeProjection({ ok: true, node: withNativeConstructEstimandV4(node, specification) });
}

export function projectNativeSemCovarianceAuthoringV4(
  edge: Edge,
  nodes: readonly Node<ConstructData>[],
  edges: readonly Edge[],
): NativeSemCovarianceAuthoringProjectionV4 {
  const source = nodes.find((node) => node.id === edge.source);
  const target = nodes.find((node) => node.id === edge.target);
  const sourceCandidates = sortedUnique(source?.data.indicators ?? []);
  const targetCandidates = sortedUnique(target?.data.indicators ?? []);
  const sourceIsEndogenous = isEndogenous(edge.source, edges);
  const targetIsEndogenous = isEndogenous(edge.target, edges);
  const diagnostics: NativeSemScientificAuthoringDiagnosticV4[] = [];
  const inspection = inspectNativeCovarianceAuthoringV4(edge);
  let choice: NativeSemCovarianceAuthoringProjectionV4["choice"] = { kind: "decision_required" };

  diagnostics.push(...baseCovarianceDiagnostics(edge, source, target));
  if (inspection.state === "invalid") {
    choice = { kind: "invalid" };
    diagnostics.push(diagnostic(
      "sem_model_v4.authoring.covariance_metadata_invalid",
      edge.id,
      `Scientific authoring details for covariance ${edge.id} cannot be read safely.`,
      "Choose one of the four relationship uses again.",
    ));
  } else if (inspection.state === "legacy_unspecified") {
    diagnostics.push(diagnostic(
      "sem_model_v4.authoring.covariance_decision_required",
      edge.id,
      `Covariance ${edge.id} still needs a scientific or presentation use.`,
      "Choose Model covariance, Residual/error covariance, Disturbance covariance, or Presentation only.",
    ));
  } else if (inspection.state === "presentation_only") {
    choice = { kind: "presentation_only" };
  } else {
    const endpoints = [inspection.specification.left, inspection.specification.right] as const;
    if (endpoints[0] === null && endpoints[1] === null) choice = { kind: "model_covariance" };
    else if (endpoints[0]?.kind === "variable" && endpoints[1]?.kind === "variable") {
      choice = { kind: "model_covariance" };
      const expected = new Set([
        nativeWorkbenchConstructVariableIdV4(edge.source),
        nativeWorkbenchConstructVariableIdV4(edge.target),
      ]);
      if (!expected.has(endpoints[0].id) || !expected.has(endpoints[1].id) || endpoints[0].id === endpoints[1].id) diagnostics.push(diagnostic(
        "sem_model_v4.authoring.model_covariance_endpoint_mismatch",
        edge.id,
        `Model covariance ${edge.id} does not reference the two constructs joined on the canvas.`,
        "Apply Model covariance again to restore endpoints from the drawn relationship.",
      ));
    } else if (endpoints[0]?.kind === "residual_of" && endpoints[1]?.kind === "residual_of") {
      const resolved = residualChoiceFromEndpoints(edge, endpoints[0].id, endpoints[1].id, sourceCandidates, targetCandidates);
      choice = resolved.choice;
      diagnostics.push(...resolved.diagnostics);
    } else if (endpoints[0]?.kind === "disturbance_of" && endpoints[1]?.kind === "disturbance_of") {
      choice = { kind: "disturbance_covariance" };
      const expected = new Set([
        nativeWorkbenchConstructVariableIdV4(edge.source),
        nativeWorkbenchConstructVariableIdV4(edge.target),
      ]);
      if (!expected.has(endpoints[0].id) || !expected.has(endpoints[1].id) || endpoints[0].id === endpoints[1].id) diagnostics.push(diagnostic(
        "sem_model_v4.authoring.disturbance_endpoint_mismatch",
        edge.id,
        `Disturbance covariance ${edge.id} does not reference the two constructs joined on the canvas.`,
        "Apply Disturbance covariance again to restore endpoints from the drawn relationship.",
      ));
      diagnostics.push(...disturbanceEligibilityDiagnostics(edge, sourceIsEndogenous, targetIsEndogenous));
    } else {
      choice = { kind: "invalid" };
      diagnostics.push(diagnostic(
        "sem_model_v4.authoring.covariance_endpoint_kinds_mixed",
        edge.id,
        `Covariance ${edge.id} mixes incompatible endpoint types.`,
        "Choose one relationship use again so both endpoints have the same scientific meaning.",
      ));
    }
  }

  return freezeProjection({
    workflow_version: SEM_MODEL_V4_SCIENTIFIC_AUTHORING_WORKFLOW_VERSION,
    edge_id: edge.id,
    choice,
    source_construct_id: edge.source,
    target_construct_id: edge.target,
    source_indicator_candidates: sourceCandidates,
    target_indicator_candidates: targetCandidates,
    source_is_endogenous: sourceIsEndogenous,
    target_is_endogenous: targetIsEndogenous,
    diagnostics: sortDiagnostics(diagnostics),
  });
}

export function validateNativeSemCovarianceChoiceV4(
  edge: Edge,
  nodes: readonly Node<ConstructData>[],
  edges: readonly Edge[],
  choice: NativeSemCovarianceDraftV4,
): readonly NativeSemScientificAuthoringDiagnosticV4[] {
  const source = nodes.find((node) => node.id === edge.source);
  const target = nodes.find((node) => node.id === edge.target);
  const diagnostics = baseCovarianceDiagnostics(edge, source, target);
  if (choice.kind === "decision_required") diagnostics.push(diagnostic(
    "sem_model_v4.authoring.covariance_decision_required",
    edge.id,
    `Covariance ${edge.id} still needs a scientific or presentation use.`,
    "Choose one of the four relationship uses.",
  ));
  else if (choice.kind === "residual_covariance") {
    if (!choice.source_indicator.trim()) diagnostics.push(diagnostic(
      "sem_model_v4.authoring.source_residual_indicator_required",
      edge.id,
      `Choose an observed indicator from ${source?.data.label || edge.source} for the first residual endpoint.`,
      "Select one of the indicators assigned to the first construct.",
    ));
    else if (!source?.data.indicators.includes(choice.source_indicator)) diagnostics.push(diagnostic(
      "sem_model_v4.authoring.source_residual_indicator_not_owned",
      edge.id,
      `${choice.source_indicator} is not assigned to ${source?.data.label || edge.source}.`,
      "Choose an indicator owned by the first construct or reconnect the covariance.",
    ));
    if (!choice.target_indicator.trim()) diagnostics.push(diagnostic(
      "sem_model_v4.authoring.target_residual_indicator_required",
      edge.id,
      `Choose an observed indicator from ${target?.data.label || edge.target} for the second residual endpoint.`,
      "Select one of the indicators assigned to the second construct.",
    ));
    else if (!target?.data.indicators.includes(choice.target_indicator)) diagnostics.push(diagnostic(
      "sem_model_v4.authoring.target_residual_indicator_not_owned",
      edge.id,
      `${choice.target_indicator} is not assigned to ${target?.data.label || edge.target}.`,
      "Choose an indicator owned by the second construct or reconnect the covariance.",
    ));
    if (choice.source_indicator.trim() && choice.source_indicator === choice.target_indicator) diagnostics.push(diagnostic(
      "sem_model_v4.authoring.residual_endpoints_not_distinct",
      edge.id,
      "A residual covariance needs two distinct observed indicators.",
      "Choose a different indicator for one endpoint.",
    ));
  } else if (choice.kind === "disturbance_covariance") {
    diagnostics.push(...disturbanceEligibilityDiagnostics(
      edge,
      isEndogenous(edge.source, edges),
      isEndogenous(edge.target, edges),
    ));
  }
  return freezeProjection(sortDiagnostics(diagnostics));
}

export function confirmNativeSemCovarianceAuthoringV4(
  edge: Edge,
  nodes: readonly Node<ConstructData>[],
  edges: readonly Edge[],
  choice: NativeSemCovarianceChoiceV4,
): NativeSemCovarianceConfirmationResultV4 {
  const diagnostics = validateNativeSemCovarianceChoiceV4(edge, nodes, edges, choice);
  if (diagnostics.length) return freezeProjection({ ok: false, diagnostics });
  if (choice.kind === "presentation_only") return freezeProjection({
    ok: true,
    edge: convertNativeCovarianceToPresentationV4(edge),
  });
  if (choice.kind === "model_covariance") return freezeProjection({
    ok: true,
    edge: convertNativeCovarianceToScientificV4(edge),
  });
  if (choice.kind === "residual_covariance") return freezeProjection({
    ok: true,
    edge: convertNativeCovarianceToScientificV4(edge, {
      left: { kind: "residual_of", id: nativeWorkbenchObservedVariableIdV4(choice.source_indicator) },
      right: { kind: "residual_of", id: nativeWorkbenchObservedVariableIdV4(choice.target_indicator) },
    }),
  });
  return freezeProjection({
    ok: true,
    edge: convertNativeCovarianceToScientificV4(edge, {
      left: { kind: "disturbance_of", id: nativeWorkbenchConstructVariableIdV4(edge.source) },
      right: { kind: "disturbance_of", id: nativeWorkbenchConstructVariableIdV4(edge.target) },
    }),
  });
}

export function nativeSemCovarianceChoiceSignatureV4(choice: NativeSemCovarianceDraftV4 | { kind: "invalid" }): string {
  if (choice.kind === "residual_covariance") return `${choice.kind}\0${choice.source_indicator}\0${choice.target_indicator}`;
  return choice.kind;
}

function baseCovarianceDiagnostics(
  edge: Edge,
  source: Node<ConstructData> | undefined,
  target: Node<ConstructData> | undefined,
): NativeSemScientificAuthoringDiagnosticV4[] {
  const diagnostics: NativeSemScientificAuthoringDiagnosticV4[] = [];
  if (edge.data?.role !== "covariance") diagnostics.push(diagnostic(
    "sem_model_v4.authoring.covariance_role_required",
    edge.id,
    `${edge.id} is not currently a covariance relationship.`,
    "Change the relationship type to Covariance before choosing its scientific use.",
  ));
  if (!source) diagnostics.push(diagnostic(
    "sem_model_v4.authoring.covariance_source_missing",
    edge.id,
    `The first construct ${edge.source} no longer exists.`,
    "Reconnect or remove this covariance.",
  ));
  if (!target) diagnostics.push(diagnostic(
    "sem_model_v4.authoring.covariance_target_missing",
    edge.id,
    `The second construct ${edge.target} no longer exists.`,
    "Reconnect or remove this covariance.",
  ));
  if (edge.source === edge.target) diagnostics.push(diagnostic(
    "sem_model_v4.authoring.covariance_self_relation",
    edge.id,
    "A covariance cannot join a construct to itself.",
    "Use a variance parameter or connect two distinct constructs.",
  ));
  return diagnostics;
}

function disturbanceEligibilityDiagnostics(
  edge: Edge,
  sourceIsEndogenous: boolean,
  targetIsEndogenous: boolean,
): NativeSemScientificAuthoringDiagnosticV4[] {
  const diagnostics: NativeSemScientificAuthoringDiagnosticV4[] = [];
  if (!sourceIsEndogenous) diagnostics.push(diagnostic(
    "sem_model_v4.authoring.disturbance_source_not_endogenous",
    edge.id,
    `${edge.source} has no incoming regression path, so it has no structural disturbance to correlate.`,
    "Use Model covariance or add an identified incoming structural path to this construct.",
  ));
  if (!targetIsEndogenous) diagnostics.push(diagnostic(
    "sem_model_v4.authoring.disturbance_target_not_endogenous",
    edge.id,
    `${edge.target} has no incoming regression path, so it has no structural disturbance to correlate.`,
    "Use Model covariance or add an identified incoming structural path to this construct.",
  ));
  return diagnostics;
}

function residualChoiceFromEndpoints(
  edge: Edge,
  leftId: string,
  rightId: string,
  sourceCandidates: readonly string[],
  targetCandidates: readonly string[],
): { choice: Extract<NativeSemCovarianceChoiceV4, { kind: "residual_covariance" }>; diagnostics: NativeSemScientificAuthoringDiagnosticV4[] } {
  const left = observedColumnFromVariableId(leftId);
  const right = observedColumnFromVariableId(rightId);
  if (sourceCandidates.includes(left) && targetCandidates.includes(right)) return {
    choice: { kind: "residual_covariance", source_indicator: left, target_indicator: right },
    diagnostics: [],
  };
  if (sourceCandidates.includes(right) && targetCandidates.includes(left)) return {
    choice: { kind: "residual_covariance", source_indicator: right, target_indicator: left },
    diagnostics: [],
  };
  return {
    choice: { kind: "residual_covariance", source_indicator: left, target_indicator: right },
    diagnostics: [diagnostic(
      "sem_model_v4.authoring.residual_endpoint_mismatch",
      edge.id,
      `Residual covariance ${edge.id} does not reference indicators owned by the two constructs joined on the canvas.`,
      "Choose one indicator from each connected construct and apply the relationship again.",
    )],
  };
}

function observedColumnFromVariableId(id: string): string {
  return id.startsWith("observed:") ? id.slice("observed:".length) : id;
}

function isEndogenous(nodeId: string, edges: readonly Edge[]): boolean {
  return edges.some((edge) => edge.target === nodeId
    && edge.source !== nodeId
    && !edge.id.startsWith("measurement::")
    && edge.data?.role !== "covariance");
}

function sortedUnique(values: readonly string[]): string[] {
  return [...new Set(values.filter((value) => typeof value === "string" && Boolean(value.trim())))].sort((left, right) => left.localeCompare(right));
}

function diagnostic(
  code: string,
  subject: string,
  message: string,
  correctiveAction: string,
): NativeSemScientificAuthoringDiagnosticV4 {
  return { code, subject, message, corrective_action: correctiveAction };
}

function sortDiagnostics(diagnostics: readonly NativeSemScientificAuthoringDiagnosticV4[]): NativeSemScientificAuthoringDiagnosticV4[] {
  return [...diagnostics].sort((left, right) => left.code.localeCompare(right.code)
    || left.subject.localeCompare(right.subject)
    || left.message.localeCompare(right.message));
}

function failure(diagnosticValue: NativeSemScientificAuthoringDiagnosticV4): NativeSemConstructConfirmationResultV4 {
  return freezeProjection({ ok: false, diagnostics: [diagnosticValue] });
}

function freezeProjection<T>(value: T): T {
  if (value && typeof value === "object" && !Object.isFrozen(value)) {
    Object.freeze(value);
    for (const child of Object.values(value as Record<string, unknown>)) freezeProjection(child);
  }
  return value;
}
