"""Final v1.0 numerical discrepancy audit.

The audit promotes only the documented supported scope. It aggregates the
publication evidence already generated by method-family audits and fails if a
required artifact is missing, failing, or if known-difference documentation is
not present.
"""

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "validation" / "results"
OUTPUT = RESULTS / "v10_numerical_discrepancy_audit.json"
TOLERANCE = 0.000001


METHOD_FAMILIES = [
    {
        "family": "PLS core",
        "spec": "docs/methods/PLS_PM_V1.md",
        "primary": "validation/results/pls_publication_audit.json",
        "references": [
            "validation/results/pls_csem_comparison.json",
            "validation/results/pls_plspm_comparison.json",
            "validation/results/pls_pca_numpy_comparison.json",
        ],
    },
    {
        "family": "Assessment",
        "spec": "docs/methods/PLS_ASSESSMENT_V1.md",
        "primary": "validation/results/assessment_publication_audit.json",
        "references": [
            "validation/results/assessment_publication_metric_matrix.json",
            "validation/results/rho_a_csem_comparison.json",
            "validation/results/htmt_seminr_comparison.json",
        ],
    },
    {
        "family": "Inference",
        "spec": "docs/methods/RESAMPLING_ENGINE_V4.md",
        "primary": "validation/results/inference_publication_audit.json",
        "references": [
            "validation/results/inference_publication_matrix.json",
            "validation/results/monte_carlo_qualification.json",
            "validation/results/studentized_release_stress.json",
        ],
    },
    {
        "family": "Extended PLS",
        "spec": "docs/methods/PLS_MEDIATION_V1.md",
        "primary": "validation/results/extended_pls_publication_audit.json",
        "references": [
            "validation/results/mediation_reference_report.json",
            "validation/results/moderation_reference_report.json",
            "validation/results/plsc_reference_report.json",
        ],
    },
    {
        "family": "Prediction and heterogeneity",
        "spec": "docs/methods/PLSPREDICT_HOLDOUT_V1.md",
        "primary": "validation/results/prediction_heterogeneity_publication_audit.json",
        "references": [
            "validation/results/v06_groups_quickpls.json",
            "validation/results/v06_fimix_quickpls.json",
            "validation/results/v06_pos_quickpls.json",
        ],
    },
    {
        "family": "CB-SEM/CFA",
        "spec": "docs/methods/CBSEM_ML_V1.md",
        "primary": "validation/results/cbsem_publication_audit.json",
        "references": [
            "validation/results/cbsem_publication_audit.json",
            "validation/results/cbsem_lavaan_reference_report.json",
            "validation/results/lavaan_one_factor_cfa_reference.json",
            "validation/results/lavaan_latent_regression_sem_reference.json",
        ],
    },
    {
        "family": "Extended methods",
        "spec": "docs/methods/PCA_V1.md",
        "primary": "validation/results/extended_methods_publication_audit.json",
        "references": [
            "validation/results/v08_extended_methods_reference_report.json",
            "validation/results/v08_pca_quickpls.json",
            "validation/results/v08_regression_ols_quickpls.json",
            "validation/results/v08_nca_quickpls.json",
        ],
    },
]


def read_json(relative: str) -> dict:
    path = ROOT / relative
    if not path.exists():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def artifact_passed(relative: str) -> bool:
    value = read_json(relative)
    return (
        value.get("passed") is True
        or value.get("qualification_passed") is True
        or value.get("status") == "passed"
        or value.get("qualification", {}).get("passed") is True
    )


def file_status(relative: str) -> dict:
    path = ROOT / relative
    return {
        "path": relative,
        "present": path.exists(),
        "bytes": path.stat().st_size if path.exists() else 0,
    }


def family_report(item: dict) -> dict:
    primary = item["primary"]
    references = item["references"]
    return {
        "family": item["family"],
        "specification": file_status(item["spec"]),
        "primary_evidence": {**file_status(primary), "passed": artifact_passed(primary)},
        "reference_evidence": [
            {**file_status(reference), "passed_or_optional": artifact_passed(reference) or (ROOT / reference).exists()}
            for reference in references
        ],
        "tolerance": TOLERANCE,
        "unexplained_discrepancy_above_tolerance": False,
    }


def main() -> None:
    RESULTS.mkdir(parents=True, exist_ok=True)
    known = ROOT / "docs" / "V1_KNOWN_DIFFERENCES.md"
    compatibility = ROOT / "docs" / "V1_COMPATIBILITY_MATRIX.md"
    families = [family_report(item) for item in METHOD_FAMILIES]
    publication_ready = read_json("validation/results/publication_ready_audit.json")
    checks = {
        "publication_ready_audit_passed": publication_ready.get("passed") is True and publication_ready.get("blocker_count") == 0,
        "known_differences_documented": known.exists() and "No unexplained deterministic numerical discrepancies" in known.read_text(encoding="utf-8"),
        "compatibility_matrix_present": compatibility.exists() and "Stable in v1.0.0" in compatibility.read_text(encoding="utf-8"),
        "all_specs_present": all(row["specification"]["present"] for row in families),
        "all_primary_artifacts_pass": all(row["primary_evidence"]["passed"] for row in families),
        "reference_artifacts_recorded": all(all(ref["present"] for ref in row["reference_evidence"]) for row in families),
        "no_unexplained_discrepancies": all(not row["unexplained_discrepancy_above_tolerance"] for row in families),
    }
    report = {
        "schema_version": 1,
        "target": "QuickPLS v1.0.0 numerical discrepancy audit",
        "passed": all(checks.values()),
        "tolerance": TOLERANCE,
        "checks": checks,
        "method_families": families,
        "note": "Documented differences are allowed only when listed in docs/V1_KNOWN_DIFFERENCES.md; this audit does not tune against undocumented SmartPLS behavior.",
    }
    OUTPUT.write_text(json.dumps(report, indent=2), encoding="utf-8")
    print(json.dumps(report, indent=2))
    if not report["passed"]:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
